### ISSUE TITLE
Problems building during package install.

### ISSUE THREAD

**Issue by SpEaGs** [intrueder/cue-sdk#5]
ran `npm install cue-sdk` and got [this. (pastebin)](https://pastebin.com/Vn2yRfwe)
Some version info:
`node -v >> v9.9.0`
`npm -v >> 5.6.0`
`node-gyp -v >> v6.1.0`

My guess is I just have to update node but I'd like to confirm before doing so.

**Comment by intrueder** [comment]
Hi @SpEaGs, thanks for reporting this

Let me check if everything is OK with the latest version of node-addon-api first.
node v9.9.0 provides NAPI v2 ( https://nodejs.org/api/n-api.html#n_api_n_api_version_matrix )
and it seems I need node-addon-api >= 1.7.1 to fix the build issue on older node version:
https://github.com/nodejs/node-addon-api/releases/tag/1.7.1

Updating node should solve the problem too.

**Comment by intrueder** [comment]
Unfortunately, having NAPI v4 is a must.
And according to version matrix https://nodejs.org/api/n-api.html#n_api_n_api_version_matrix
your node should be at least v10.16.0 (v8.16.0 will work too, but it's a downgrade in this case)

**Comment by intrueder** [comment]
Added this requirement to readme f07008722e6ad122c5badd094b33f9684df41ea8
